[[todos]]
title="Create sublimetext plugin for managing tasks"
details="I like using sublimegit and I am bad at managing my own tasks. Why not make this a thing?"
created_on="2021-06-08 11:27:01.452038"

[[todos]]
title="Create file format to store tasks"
created_on="2021-06-08 11:27:01.452038"

[[doings]]
title="Decide on a name for sublimetext task management plugin"
created_on="2021-06-08 11:27:01.452038"

[[dones]]
title="Create simple storage backend for tasks"
created_on="2021-06-08 11:27:01.452038"
completed_on="2021-06-08 11:27:01.452038"

[[notes]]
title="Long lived reminder; call your mother"
created_on="2021-06-08 11:27:01.452038"

